// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.27.1
// source: tiktok-schema.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "TikTok";

export interface WebcastResponse {
  messages: WebcastResponse_Message[];
  cursor: string;
  fetchInterval: string;
  now: string;
  internalExt: string;
  fetchType: number;
  routeParamsMap: { [key: string]: string };
  heartBeatDuration: string;
  needsAck: boolean;
  pushServer: string;
  isFirst: boolean;
  historyCommentCursor: string;
  historyNoMore: boolean;
}

export interface WebcastResponse_RouteParamsMapEntry {
  key: string;
  value: string;
}

export interface WebcastResponse_Message {
  method: string;
  payload: Uint8Array;
  msgId: string;
  msgType: number;
  offset: string;
  isHistory: boolean;
}

function createBaseWebcastResponse(): WebcastResponse {
  return {
    messages: [],
    cursor: "",
    fetchInterval: "0",
    now: "0",
    internalExt: "",
    fetchType: 0,
    routeParamsMap: {},
    heartBeatDuration: "0",
    needsAck: false,
    pushServer: "",
    isFirst: false,
    historyCommentCursor: "",
    historyNoMore: false,
  };
}

export const WebcastResponse: MessageFns<WebcastResponse> = {
  encode(message: WebcastResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.messages) {
      WebcastResponse_Message.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.cursor !== "") {
      writer.uint32(18).string(message.cursor);
    }
    if (message.fetchInterval !== "0") {
      writer.uint32(24).int64(message.fetchInterval);
    }
    if (message.now !== "0") {
      writer.uint32(32).int64(message.now);
    }
    if (message.internalExt !== "") {
      writer.uint32(42).string(message.internalExt);
    }
    if (message.fetchType !== 0) {
      writer.uint32(48).int32(message.fetchType);
    }
    Object.entries(message.routeParamsMap).forEach(([key, value]) => {
      WebcastResponse_RouteParamsMapEntry.encode({ key: key as any, value }, writer.uint32(58).fork()).join();
    });
    if (message.heartBeatDuration !== "0") {
      writer.uint32(64).int64(message.heartBeatDuration);
    }
    if (message.needsAck !== false) {
      writer.uint32(72).bool(message.needsAck);
    }
    if (message.pushServer !== "") {
      writer.uint32(82).string(message.pushServer);
    }
    if (message.isFirst !== false) {
      writer.uint32(88).bool(message.isFirst);
    }
    if (message.historyCommentCursor !== "") {
      writer.uint32(98).string(message.historyCommentCursor);
    }
    if (message.historyNoMore !== false) {
      writer.uint32(104).bool(message.historyNoMore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WebcastResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebcastResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.messages.push(WebcastResponse_Message.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.fetchInterval = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.now = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.internalExt = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.fetchType = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = WebcastResponse_RouteParamsMapEntry.decode(reader, reader.uint32());
          if (entry7.value !== undefined) {
            message.routeParamsMap[entry7.key] = entry7.value;
          }
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.heartBeatDuration = reader.int64().toString();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.needsAck = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.pushServer = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.isFirst = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.historyCommentCursor = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.historyNoMore = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WebcastResponse {
    return {
      messages: globalThis.Array.isArray(object?.messages)
        ? object.messages.map((e: any) => WebcastResponse_Message.fromJSON(e))
        : [],
      cursor: isSet(object.cursor) ? globalThis.String(object.cursor) : "",
      fetchInterval: isSet(object.fetchInterval) ? globalThis.String(object.fetchInterval) : "0",
      now: isSet(object.now) ? globalThis.String(object.now) : "0",
      internalExt: isSet(object.internalExt) ? globalThis.String(object.internalExt) : "",
      fetchType: isSet(object.fetchType) ? globalThis.Number(object.fetchType) : 0,
      routeParamsMap: isObject(object.routeParamsMap)
        ? Object.entries(object.routeParamsMap).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      heartBeatDuration: isSet(object.heartBeatDuration) ? globalThis.String(object.heartBeatDuration) : "0",
      needsAck: isSet(object.needsAck) ? globalThis.Boolean(object.needsAck) : false,
      pushServer: isSet(object.pushServer) ? globalThis.String(object.pushServer) : "",
      isFirst: isSet(object.isFirst) ? globalThis.Boolean(object.isFirst) : false,
      historyCommentCursor: isSet(object.historyCommentCursor) ? globalThis.String(object.historyCommentCursor) : "",
      historyNoMore: isSet(object.historyNoMore) ? globalThis.Boolean(object.historyNoMore) : false,
    };
  },

  toJSON(message: WebcastResponse): unknown {
    const obj: any = {};
    if (message.messages?.length) {
      obj.messages = message.messages.map((e) => WebcastResponse_Message.toJSON(e));
    }
    if (message.cursor !== "") {
      obj.cursor = message.cursor;
    }
    if (message.fetchInterval !== "0") {
      obj.fetchInterval = message.fetchInterval;
    }
    if (message.now !== "0") {
      obj.now = message.now;
    }
    if (message.internalExt !== "") {
      obj.internalExt = message.internalExt;
    }
    if (message.fetchType !== 0) {
      obj.fetchType = Math.round(message.fetchType);
    }
    if (message.routeParamsMap) {
      const entries = Object.entries(message.routeParamsMap);
      if (entries.length > 0) {
        obj.routeParamsMap = {};
        entries.forEach(([k, v]) => {
          obj.routeParamsMap[k] = v;
        });
      }
    }
    if (message.heartBeatDuration !== "0") {
      obj.heartBeatDuration = message.heartBeatDuration;
    }
    if (message.needsAck !== false) {
      obj.needsAck = message.needsAck;
    }
    if (message.pushServer !== "") {
      obj.pushServer = message.pushServer;
    }
    if (message.isFirst !== false) {
      obj.isFirst = message.isFirst;
    }
    if (message.historyCommentCursor !== "") {
      obj.historyCommentCursor = message.historyCommentCursor;
    }
    if (message.historyNoMore !== false) {
      obj.historyNoMore = message.historyNoMore;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WebcastResponse>, I>>(base?: I): WebcastResponse {
    return WebcastResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WebcastResponse>, I>>(object: I): WebcastResponse {
    const message = createBaseWebcastResponse();
    message.messages = object.messages?.map((e) => WebcastResponse_Message.fromPartial(e)) || [];
    message.cursor = object.cursor ?? "";
    message.fetchInterval = object.fetchInterval ?? "0";
    message.now = object.now ?? "0";
    message.internalExt = object.internalExt ?? "";
    message.fetchType = object.fetchType ?? 0;
    message.routeParamsMap = Object.entries(object.routeParamsMap ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.heartBeatDuration = object.heartBeatDuration ?? "0";
    message.needsAck = object.needsAck ?? false;
    message.pushServer = object.pushServer ?? "";
    message.isFirst = object.isFirst ?? false;
    message.historyCommentCursor = object.historyCommentCursor ?? "";
    message.historyNoMore = object.historyNoMore ?? false;
    return message;
  },
};

function createBaseWebcastResponse_RouteParamsMapEntry(): WebcastResponse_RouteParamsMapEntry {
  return { key: "", value: "" };
}

export const WebcastResponse_RouteParamsMapEntry: MessageFns<WebcastResponse_RouteParamsMapEntry> = {
  encode(message: WebcastResponse_RouteParamsMapEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WebcastResponse_RouteParamsMapEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebcastResponse_RouteParamsMapEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WebcastResponse_RouteParamsMapEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: WebcastResponse_RouteParamsMapEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WebcastResponse_RouteParamsMapEntry>, I>>(
    base?: I,
  ): WebcastResponse_RouteParamsMapEntry {
    return WebcastResponse_RouteParamsMapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WebcastResponse_RouteParamsMapEntry>, I>>(
    object: I,
  ): WebcastResponse_RouteParamsMapEntry {
    const message = createBaseWebcastResponse_RouteParamsMapEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseWebcastResponse_Message(): WebcastResponse_Message {
  return { method: "", payload: new Uint8Array(0), msgId: "0", msgType: 0, offset: "0", isHistory: false };
}

export const WebcastResponse_Message: MessageFns<WebcastResponse_Message> = {
  encode(message: WebcastResponse_Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== "") {
      writer.uint32(10).string(message.method);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    if (message.msgId !== "0") {
      writer.uint32(24).int64(message.msgId);
    }
    if (message.msgType !== 0) {
      writer.uint32(32).int32(message.msgType);
    }
    if (message.offset !== "0") {
      writer.uint32(40).int64(message.offset);
    }
    if (message.isHistory !== false) {
      writer.uint32(48).bool(message.isHistory);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WebcastResponse_Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebcastResponse_Message();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.msgId = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.msgType = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.offset = reader.int64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isHistory = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WebcastResponse_Message {
    return {
      method: isSet(object.method) ? globalThis.String(object.method) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      msgId: isSet(object.msgId) ? globalThis.String(object.msgId) : "0",
      msgType: isSet(object.msgType) ? globalThis.Number(object.msgType) : 0,
      offset: isSet(object.offset) ? globalThis.String(object.offset) : "0",
      isHistory: isSet(object.isHistory) ? globalThis.Boolean(object.isHistory) : false,
    };
  },

  toJSON(message: WebcastResponse_Message): unknown {
    const obj: any = {};
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.msgId !== "0") {
      obj.msgId = message.msgId;
    }
    if (message.msgType !== 0) {
      obj.msgType = Math.round(message.msgType);
    }
    if (message.offset !== "0") {
      obj.offset = message.offset;
    }
    if (message.isHistory !== false) {
      obj.isHistory = message.isHistory;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WebcastResponse_Message>, I>>(base?: I): WebcastResponse_Message {
    return WebcastResponse_Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WebcastResponse_Message>, I>>(object: I): WebcastResponse_Message {
    const message = createBaseWebcastResponse_Message();
    message.method = object.method ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    message.msgId = object.msgId ?? "0";
    message.msgType = object.msgType ?? 0;
    message.offset = object.offset ?? "0";
    message.isHistory = object.isHistory ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
